Old Documentation

- [`whos`](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-whos)
- [`import`](https://docs.python.org/3/reference/simple_stmts.html#the-import-statement)
- [`module`](https://docs.python.org/3/tutorial/modules.html)
- [`del`](https://docs.python.org/3/reference/simple_stmts.html#the-del-statement)
- [`print`](https://docs.python.org/3/library/functions.html#print)

New Documetation
- [`torch`](https://pytorch.org/docs/stable/index.html)
- [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)
- [`torch.save`](https://pytorch.org/docs/stable/generated/torch.save.html)
- [`torch.load`](https://pytorch.org/docs/stable/generated/torch.load.html)

Print the current variables stored in this environment.

In [1]:
%whos

Interactive namespace is empty.


Import the numpy module.

In [2]:
import torch

In [3]:
%whos

Variable   Type      Data/Info
------------------------------
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


---
Create matrix $A$ as a torch tensor.

$A = 
    \begin{bmatrix}
        3.4 & 5.4 & 2.9 & 7.3 & 2.0 & 9.0 \\
        5.7 & 5.2 & 2.2 & 8.0 & 4.0 & 6.5 \\
        1.6 & 7.5 & 2.7 & 0.8 & 0.3 & 0.3 \\
        1.6 & 4.7 & 4.4 & 3.7 & 6.8 & 7.1
    \end{bmatrix} $
    

In [5]:
A = torch.Tensor([[3.4, 5.4, 2.9, 7.3, 2.0, 9.0],
                  [5.7, 5.2, 2.2, 8.0, 4.0, 6.5],
                  [1.6, 7.5, 2.7, 0.8, 0.3, 0.3],
                  [1.6, 4.7, 4.4, 3.7, 6.8, 7.1]])

In [7]:
print(A)

tensor([[3.4000, 5.4000, 2.9000, 7.3000, 2.0000, 9.0000],
        [5.7000, 5.2000, 2.2000, 8.0000, 4.0000, 6.5000],
        [1.6000, 7.5000, 2.7000, 0.8000, 0.3000, 0.3000],
        [1.6000, 4.7000, 4.4000, 3.7000, 6.8000, 7.1000]])


In [6]:
%whos

Variable   Type      Data/Info
------------------------------
A          Tensor    tensor([[3.4000, 5.4000, <...>3.7000, 6.8000, 7.1000]])
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


Save matrix $A$ as a pt file.

In [8]:
torch.save(A, "A.pt")

Delete local matrix $A$ from environment.

In [9]:
del A

In [10]:
%whos

Variable   Type      Data/Info
------------------------------
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


Load previously saved matrix $A$ to environment.

In [11]:
A = torch.load("A.pt")

In [12]:
%whos

Variable   Type      Data/Info
------------------------------
A          Tensor    tensor([[3.4000, 5.4000, <...>3.7000, 6.8000, 7.1000]])
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


In [13]:
print(A)

tensor([[3.4000, 5.4000, 2.9000, 7.3000, 2.0000, 9.0000],
        [5.7000, 5.2000, 2.2000, 8.0000, 4.0000, 6.5000],
        [1.6000, 7.5000, 2.7000, 0.8000, 0.3000, 0.3000],
        [1.6000, 4.7000, 4.4000, 3.7000, 6.8000, 7.1000]])


---
Create matrix $B$ as a torch tensor.

$B = 
    \begin{bmatrix}
        4 & 2 & 1 & 2 \\
        9 & 9 & 6 & 4 \\
        9 & 5 & 3 & 5 \\
        7 & 8 & 4 & 7 \\
        0 & 4 & 1 & 0 \\
        4 & 5 & 2 & 1
    \end{bmatrix} $

In [14]:
B = torch.Tensor([[4, 2, 1, 2],
                  [9, 9, 6, 4],
                  [9, 5, 3, 5],
                  [7, 8, 4, 7],
                  [0, 4, 1, 0],
                  [4, 5, 2, 1]])

In [16]:
print(B)

tensor([[4., 2., 1., 2.],
        [9., 9., 6., 4.],
        [9., 5., 3., 5.],
        [7., 8., 4., 7.],
        [0., 4., 1., 0.],
        [4., 5., 2., 1.]])


In [15]:
%whos

Variable   Type      Data/Info
------------------------------
A          Tensor    tensor([[3.4000, 5.4000, <...>3.7000, 6.8000, 7.1000]])
B          Tensor    tensor([[4., 2., 1., 2.],<...>       [4., 5., 2., 1.]])
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


Save matrix $B$ as a pt file.

In [17]:
torch.save(B, "B.pt")

Delete local matrix $B$ from environment.

In [18]:
del B

In [19]:
%whos

Variable   Type      Data/Info
------------------------------
A          Tensor    tensor([[3.4000, 5.4000, <...>3.7000, 6.8000, 7.1000]])
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


Load previously saved matrix $B$ to environment.

In [20]:
B = torch.load("B.pt")

In [22]:
print(B)

tensor([[4., 2., 1., 2.],
        [9., 9., 6., 4.],
        [9., 5., 3., 5.],
        [7., 8., 4., 7.],
        [0., 4., 1., 0.],
        [4., 5., 2., 1.]])


In [21]:
%whos

Variable   Type      Data/Info
------------------------------
A          Tensor    tensor([[3.4000, 5.4000, <...>3.7000, 6.8000, 7.1000]])
B          Tensor    tensor([[4., 2., 1., 2.],<...>       [4., 5., 2., 1.]])
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


Create list of matrices, $C$, containing matrices $A$ and $B$.

In [23]:
C = [A, B]

In [25]:
print(C)

[tensor([[3.4000, 5.4000, 2.9000, 7.3000, 2.0000, 9.0000],
        [5.7000, 5.2000, 2.2000, 8.0000, 4.0000, 6.5000],
        [1.6000, 7.5000, 2.7000, 0.8000, 0.3000, 0.3000],
        [1.6000, 4.7000, 4.4000, 3.7000, 6.8000, 7.1000]]), tensor([[4., 2., 1., 2.],
        [9., 9., 6., 4.],
        [9., 5., 3., 5.],
        [7., 8., 4., 7.],
        [0., 4., 1., 0.],
        [4., 5., 2., 1.]])]


In [24]:
%whos

Variable   Type      Data/Info
------------------------------
A          Tensor    tensor([[3.4000, 5.4000, <...>3.7000, 6.8000, 7.1000]])
B          Tensor    tensor([[4., 2., 1., 2.],<...>       [4., 5., 2., 1.]])
C          list      n=2
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


Save array of matrices, $C$, as one pt file.

In [26]:
torch.save(C, "C.pt")

Delete array of matrices, $C$, from environment.

In [27]:
del C

In [28]:
%whos

Variable   Type      Data/Info
------------------------------
A          Tensor    tensor([[3.4000, 5.4000, <...>3.7000, 6.8000, 7.1000]])
B          Tensor    tensor([[4., 2., 1., 2.],<...>       [4., 5., 2., 1.]])
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>


In [29]:
C = torch.load("C.pt")

In [30]:
%whos

Variable   Type      Data/Info
------------------------------
A          Tensor    tensor([[3.4000, 5.4000, <...>3.7000, 6.8000, 7.1000]])
B          Tensor    tensor([[4., 2., 1., 2.],<...>       [4., 5., 2., 1.]])
C          list      n=2
torch      module    <module 'torch' from '/ho<...>kages/torch/__init__.py'>
