Old Documentation

- [`import`](https://docs.python.org/3/reference/simple_stmts.html#the-import-statement)
- [`len`](https://docs.python.org/3/library/functions.html#len)
- [`numpy`](https://numpy.org/doc/1.19/user/whatisnumpy.html)
- [`numpy.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html)
- [`numpy.load`](https://numpy.org/doc/stable/reference/generated/numpy.load.html)

New Documentation
- [`numpy.ndarray.shape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html)

Import the numpy module.

In [1]:
import numpy as np

Load matrix A to environment.

In [2]:
A = np.load("./samples/A.npy")

In [3]:
print(A)

[[3.4 5.4 2.9 7.3 2.  9. ]
 [5.7 5.2 2.2 8.  4.  6.5]
 [1.6 7.5 2.7 0.8 0.3 0.3]
 [1.6 4.7 4.4 3.7 6.8 7.1]]


Get the number of rows in matrix A using the len function.

In [4]:
A_length = len(A)

In [5]:
print(A_length)

4


Get the number of rows and columns of matrix A using the shape attribute.

In [6]:
A_shape = A.shape

In [7]:
print(A_shape)

(4, 6)


Index the shape attribute of matrix A to get the number of rows.

In [8]:
A_nrows = A.shape[0]

In [9]:
print(A_nrows)

4


Index the column attribute of matrix A to get the number of columns.

In [10]:
A_ncols = A.shape[1]

In [11]:
print(A_ncols)

6


Load matrix B to environment.

In [12]:
B = np.load("./samples/B.npy")

In [13]:
print(B)

[[4 2 1 2]
 [9 9 6 4]
 [9 5 3 5]
 [7 8 4 7]
 [0 4 1 0]
 [4 5 2 1]]


Get the number of rows in matrix B using the len function.

In [14]:
B_length = len(B)

In [15]:
print(B_length)

6


Get the number of rows and columns of matrix B using the shape attribute.

In [16]:
B.shape

(6, 4)

Index the shape attribute of matrix B to get the number of rows.

In [17]:
B_nrows = B.shape[0]

In [18]:
print(B_nrows)

6


Index the column attribute of matrix A to get the number of columns.

In [19]:
B_ncols = B.shape[1]

In [20]:
print(B_ncols)

4


Load array of matrices, C, to environment.

In [21]:
C = np.load("./samples/C.npy", allow_pickle=True)

Print the number of matrices in C using the len function.

In [22]:
len(C)

2

Print the number of matrices in C using the shape attribute.

In [23]:
C.shape

(2,)

Print the number of rows in matrix 0 of C by indexing and using the len function.

In [24]:
len(C[0])

4

Print the number of rows and columns in matrix 0 of C by indexing and using the shape attribute.

In [25]:
C[0].shape

(4, 6)

Print the number of rows in matrix 1 of C by indexing and using the len function.

In [26]:
len(C[1])

6

Print the number of rows and columns in matrix 1 of C by indexing and using the shape attribute.

In [27]:
C[1].shape

(6, 4)