In [1]:
import numpy as np

A = np.load("A.npy")

In [2]:
A

array([[3.4, 5.4, 2.9, 7.3, 2. , 9. ],
       [5.7, 5.2, 2.2, 8. , 4. , 6.5],
       [1.6, 7.5, 2.7, 0.8, 0.3, 0.3],
       [1.6, 4.7, 4.4, 3.7, 6.8, 7.1]])

Select column 3 from matrix A.

In [3]:
A[:, 3]

array([7.3, 8. , 0.8, 3.7])

Select column 0 up to but not including column 4 from matrix A.

In [4]:
A[:, :4]

array([[3.4, 5.4, 2.9, 7.3],
       [5.7, 5.2, 2.2, 8. ],
       [1.6, 7.5, 2.7, 0.8],
       [1.6, 4.7, 4.4, 3.7]])

Select column 0 up to and including column 4 from matrix A.

In [5]:
A[:, :(4+1)]

array([[3.4, 5.4, 2.9, 7.3, 2. ],
       [5.7, 5.2, 2.2, 8. , 4. ],
       [1.6, 7.5, 2.7, 0.8, 0.3],
       [1.6, 4.7, 4.4, 3.7, 6.8]])

Select column 3 up to and including column 5 from matrix A.

In [6]:
A[:, 3:(5+1)]

array([[7.3, 2. , 9. ],
       [8. , 4. , 6.5],
       [0.8, 0.3, 0.3],
       [3.7, 6.8, 7.1]])

Select the last column of matrix A.

In [7]:
A[:, -1]

array([9. , 6.5, 0.3, 7.1])

Select column 4 up to but not including the last column of matrix A

In [8]:
A[:, 4:-1]

array([[2. ],
       [4. ],
       [0.3],
       [6.8]])

Select column 4 up to and including the last column of matrix A

In [9]:
A[:, 4:]

array([[2. , 9. ],
       [4. , 6.5],
       [0.3, 0.3],
       [6.8, 7.1]])

---

Select row 2 from matrix A

In [10]:
A[2, :]

array([1.6, 7.5, 2.7, 0.8, 0.3, 0.3])

Select row 1 up to but not including row 3 from matrix A

In [11]:
A[1:3, :]

array([[5.7, 5.2, 2.2, 8. , 4. , 6.5],
       [1.6, 7.5, 2.7, 0.8, 0.3, 0.3]])

Select row 2 up to and including the last row of matrix A

In [12]:
A[2:, :]

array([[1.6, 7.5, 2.7, 0.8, 0.3, 0.3],
       [1.6, 4.7, 4.4, 3.7, 6.8, 7.1]])

---

Select column 0 up to and including column 2, and select row 3 up to and including row 4 of matrix A.

In [13]:
A[3:(4+1), :(2+1)]

array([[1.6, 4.7, 4.4]])

Select row 1 up to but not including row 3, and column 1 up to and including column 5.

In [14]:
A[1:3, 1:(5+1)]

array([[5.2, 2.2, 8. , 4. , 6.5],
       [7.5, 2.7, 0.8, 0.3, 0.3]])