In [1]:
import torch

A = torch.load("A.pt")

In [2]:
A

tensor([[3.4000, 5.4000, 2.9000, 7.3000, 2.0000, 9.0000],
        [5.7000, 5.2000, 2.2000, 8.0000, 4.0000, 6.5000],
        [1.6000, 7.5000, 2.7000, 0.8000, 0.3000, 0.3000],
        [1.6000, 4.7000, 4.4000, 3.7000, 6.8000, 7.1000]])

Select column 3 from matrix A.

In [3]:
A[:, 3]

tensor([7.3000, 8.0000, 0.8000, 3.7000])

Select column 0 up to but not including column 4 from matrix A.

In [4]:
A[:, :4]

tensor([[3.4000, 5.4000, 2.9000, 7.3000],
        [5.7000, 5.2000, 2.2000, 8.0000],
        [1.6000, 7.5000, 2.7000, 0.8000],
        [1.6000, 4.7000, 4.4000, 3.7000]])

Select column 0 up to and including column 4 from matrix A.

In [5]:
A[:, :(4+1)]

tensor([[3.4000, 5.4000, 2.9000, 7.3000, 2.0000],
        [5.7000, 5.2000, 2.2000, 8.0000, 4.0000],
        [1.6000, 7.5000, 2.7000, 0.8000, 0.3000],
        [1.6000, 4.7000, 4.4000, 3.7000, 6.8000]])

Select column 3 up to and including column 5 from matrix A.

In [6]:
A[:, 3:(5+1)]

tensor([[7.3000, 2.0000, 9.0000],
        [8.0000, 4.0000, 6.5000],
        [0.8000, 0.3000, 0.3000],
        [3.7000, 6.8000, 7.1000]])

Select the last column of matrix A.

In [7]:
A[:, -1]

tensor([9.0000, 6.5000, 0.3000, 7.1000])

Select column 4 up to but not including the last column of matrix A

In [8]:
A[:, 4:-1]

tensor([[2.0000],
        [4.0000],
        [0.3000],
        [6.8000]])

Select column 4 up to and including the last column of matrix A

In [9]:
A[:, 4:]

tensor([[2.0000, 9.0000],
        [4.0000, 6.5000],
        [0.3000, 0.3000],
        [6.8000, 7.1000]])

---

Select row 2 from matrix A

In [10]:
A[2, :]

tensor([1.6000, 7.5000, 2.7000, 0.8000, 0.3000, 0.3000])

Select row 1 up to but not including row 3 from matrix A

In [11]:
A[1:3, :]

tensor([[5.7000, 5.2000, 2.2000, 8.0000, 4.0000, 6.5000],
        [1.6000, 7.5000, 2.7000, 0.8000, 0.3000, 0.3000]])

Select row 2 up to and including the last row of matrix A

In [12]:
A[2:, :]

tensor([[1.6000, 7.5000, 2.7000, 0.8000, 0.3000, 0.3000],
        [1.6000, 4.7000, 4.4000, 3.7000, 6.8000, 7.1000]])

---

Select column 0 up to and including column 2, and select row 3 up to and including row 4 of matrix A.

In [13]:
A[3:(4+1), :(2+1)]

tensor([[1.6000, 4.7000, 4.4000]])

Select row 1 up to but not including row 3, and column 1 up to and including column 5.

In [14]:
A[1:3, 1:(5+1)]

tensor([[5.2000, 2.2000, 8.0000, 4.0000, 6.5000],
        [7.5000, 2.7000, 0.8000, 0.3000, 0.3000]])