In [1]:
import numpy as np

spectrogram = np.load("./samples/spectrograms/linear/spectrogram-1.npy")

In [2]:
spectrogram

array([[1.16202896e+02, 2.48041809e+02, 1.99960464e+02, ...,
        1.20060656e-06, 6.61158992e-07, 1.26304428e-07],
       [5.21318512e+01, 9.25250879e+03, 7.51781433e+02, ...,
        8.44873739e-06, 9.50663775e-07, 3.29908175e-07],
       [5.98239380e+02, 2.74541875e+04, 3.53477773e+04, ...,
        5.35508377e-07, 1.29701152e-06, 1.08094105e-06],
       ...,
       [4.43745852e-02, 7.46453356e-04, 1.30632857e-03, ...,
        1.64346747e-09, 8.79429649e-08, 9.14265215e-08],
       [3.62345941e-06, 3.78491910e-04, 2.82683068e-05, ...,
        8.21975789e-07, 1.29495021e-07, 2.62450666e-08],
       [1.64031666e-09, 2.14223164e-07, 1.67822904e-07, ...,
        2.09960575e-07, 2.09960533e-07, 1.04980266e-07]], dtype=float32)

(frequency, timesteps)

In [3]:
spectrogram.shape

(1663, 129)

---

Select all frequencies starting at timestep 0 and ending at timestep 5 (exclusive)

In [4]:
spectrogram[0:5, :]

array([[1.16202896e+02, 2.48041809e+02, 1.99960464e+02, 1.45435638e+02,
        1.01057945e+02, 7.24315567e+01, 5.68193054e+01, 4.52664337e+01,
        3.20386429e+01, 1.94577599e+01, 1.08531399e+01, 5.60546207e+00,
        2.62938905e+00, 1.00340152e+00, 3.16084474e-01, 9.50481296e-02,
        7.83967674e-02, 9.02059376e-02, 1.06279306e-01, 7.37971663e-02,
        4.64652032e-02, 2.40745787e-02, 5.34388842e-03, 2.42794701e-03,
        9.67797916e-03, 2.12214980e-02, 2.95700673e-02, 4.05911095e-02,
        5.53005897e-02, 5.48254400e-02, 6.19653575e-02, 6.31924272e-02,
        5.40411919e-02, 5.21595366e-02, 4.62052599e-02, 3.51080522e-02,
        3.70109193e-02, 3.76182124e-02, 4.36160080e-02, 5.58867902e-02,
        6.75567612e-02, 7.16999397e-02, 8.80703554e-02, 8.43872353e-02,
        8.48762617e-02, 8.43779147e-02, 7.39186332e-02, 5.95110580e-02,
        5.98556586e-02, 3.90191860e-02, 3.41461152e-02, 2.80036461e-02,
        1.58218108e-02, 1.40157714e-02, 1.12300385e-02, 4.797169

Select all frequencies at timestep 2

In [5]:
spectrogram[2, :]

array([5.98239380e+02, 2.74541875e+04, 3.53477773e+04, 3.15156738e+04,
       1.84253770e+04, 7.13962646e+03, 9.66301855e+03, 3.65124292e+03,
       2.99453491e+02, 3.10297913e+02, 1.09302010e+02, 2.99994904e+02,
       2.24057114e+02, 9.62954163e+02, 2.64477319e+03, 6.62720442e+00,
       7.33846998e+00, 5.84862442e+01, 3.99962585e+02, 1.52775909e+02,
       1.37684952e+02, 3.05205798e+00, 1.66778965e+01, 1.33517275e+01,
       8.20626640e+00, 1.20644131e+01, 1.37364683e+01, 8.29719162e+00,
       2.96770424e-01, 1.91351485e+00, 2.23303223e+00, 2.94278526e+01,
       2.28387089e+01, 8.11023295e-01, 2.12475090e+01, 3.05098877e+01,
       3.87183647e+01, 1.10479174e+01, 3.81021652e+01, 2.55442715e+01,
       4.57111262e-02, 1.44272614e+01, 2.04264611e-01, 3.27585340e-01,
       1.21976035e-02, 6.58916831e-02, 1.41348764e-01, 3.30045051e-03,
       2.94493049e-01, 9.96059060e-01, 4.73477036e-01, 3.22207403e+00,
       5.45185661e+00, 1.12025172e-01, 4.00439240e-02, 8.76928121e-03,
      

Select all frequencies at timestep 2 with a context size of 1

In [6]:
spectrogram[(2-1):(2+1+1)]

array([[5.21318512e+01, 9.25250879e+03, 7.51781433e+02, 5.72211377e+03,
        1.71387744e+03, 3.73619019e+02, 6.94112671e+02, 6.25717102e+02,
        1.60706497e+02, 3.59295769e+01, 2.02941456e+01, 2.43163013e+01,
        1.86761551e+01, 2.51718178e+01, 1.13235486e+03, 2.94970703e+02,
        2.97737808e+01, 1.56789064e+01, 4.52347488e+01, 2.77299271e+01,
        2.65748978e+01, 7.29109526e-01, 2.19911518e+01, 1.33913755e+00,
        4.71006572e-01, 2.96418101e-01, 1.13350594e+00, 7.51989901e-01,
        1.22662807e+00, 3.31521702e+00, 5.37514591e+00, 7.23831863e+01,
        4.29079008e+00, 2.76981468e+01, 3.64376526e+01, 1.50612307e+01,
        1.25151520e+01, 6.95568037e+00, 8.13076615e-01, 1.31655674e+01,
        3.80344849e+01, 2.48862247e+01, 2.20065022e+01, 6.39649439e+00,
        1.44662708e-01, 5.01794890e-02, 9.27642509e-02, 1.74444348e-01,
        3.64759974e-02, 3.95134956e-01, 6.95095241e-01, 7.21116289e-02,
        4.93068457e-01, 2.81033725e-01, 1.04734145e-01, 5.235288

Select all frequencies at timestep 2 with a context size of 2

In [7]:
spectrogram[(2-2):(2+2+1)]

array([[1.16202896e+02, 2.48041809e+02, 1.99960464e+02, 1.45435638e+02,
        1.01057945e+02, 7.24315567e+01, 5.68193054e+01, 4.52664337e+01,
        3.20386429e+01, 1.94577599e+01, 1.08531399e+01, 5.60546207e+00,
        2.62938905e+00, 1.00340152e+00, 3.16084474e-01, 9.50481296e-02,
        7.83967674e-02, 9.02059376e-02, 1.06279306e-01, 7.37971663e-02,
        4.64652032e-02, 2.40745787e-02, 5.34388842e-03, 2.42794701e-03,
        9.67797916e-03, 2.12214980e-02, 2.95700673e-02, 4.05911095e-02,
        5.53005897e-02, 5.48254400e-02, 6.19653575e-02, 6.31924272e-02,
        5.40411919e-02, 5.21595366e-02, 4.62052599e-02, 3.51080522e-02,
        3.70109193e-02, 3.76182124e-02, 4.36160080e-02, 5.58867902e-02,
        6.75567612e-02, 7.16999397e-02, 8.80703554e-02, 8.43872353e-02,
        8.48762617e-02, 8.43779147e-02, 7.39186332e-02, 5.95110580e-02,
        5.98556586e-02, 3.90191860e-02, 3.41461152e-02, 2.80036461e-02,
        1.58218108e-02, 1.40157714e-02, 1.12300385e-02, 4.797169

Select all frequencies at timestep 0 with a context size of 2 (Fails Silently)

In [8]:
# ### Fails silently, not returning intended result
# spectrogram[(0-2):(0+2+1)]

# ### Returns:
# ### array([], shape=(0, 129), dtype=float32)

Zero pad spectrogram with an offset of 2

In [9]:
padded_spectrogram = np.pad(spectrogram, ((2,2),(0,0)), "constant", constant_values=0)

In [10]:
padded_spectrogram[(0+2-2):(0+2+2+1), :]

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.000000

In [11]:
context = 2
offset = 2

# Define reference (center) index j
j = 0

# Define starting timestep j
start_j = j + offset - context

# Define ending timestep j
end_j = j + offset + context + 1

### Get data at index pair with context (1 line)
frames = spectrogram[start_j:end_j,:]

In [12]:
frames

array([[1.16202896e+02, 2.48041809e+02, 1.99960464e+02, 1.45435638e+02,
        1.01057945e+02, 7.24315567e+01, 5.68193054e+01, 4.52664337e+01,
        3.20386429e+01, 1.94577599e+01, 1.08531399e+01, 5.60546207e+00,
        2.62938905e+00, 1.00340152e+00, 3.16084474e-01, 9.50481296e-02,
        7.83967674e-02, 9.02059376e-02, 1.06279306e-01, 7.37971663e-02,
        4.64652032e-02, 2.40745787e-02, 5.34388842e-03, 2.42794701e-03,
        9.67797916e-03, 2.12214980e-02, 2.95700673e-02, 4.05911095e-02,
        5.53005897e-02, 5.48254400e-02, 6.19653575e-02, 6.31924272e-02,
        5.40411919e-02, 5.21595366e-02, 4.62052599e-02, 3.51080522e-02,
        3.70109193e-02, 3.76182124e-02, 4.36160080e-02, 5.58867902e-02,
        6.75567612e-02, 7.16999397e-02, 8.80703554e-02, 8.43872353e-02,
        8.48762617e-02, 8.43779147e-02, 7.39186332e-02, 5.95110580e-02,
        5.98556586e-02, 3.90191860e-02, 3.41461152e-02, 2.80036461e-02,
        1.58218108e-02, 1.40157714e-02, 1.12300385e-02, 4.797169